// src/pages/robots.txt.ts
// ─────────────────────────────────────────────────────────────────
// This file REPLACES the static public/robots.txt
// DELETE public/robots.txt after adding this file.
//
// WHY THIS IS BETTER THAN A STATIC FILE:
// - Astro generates it at build time so it's always correct
// - Sitemap URL is automatically correct (uses your site config)
// - You can add logic: e.g. block pages based on environment
// - In future: if you add a /admin page, just add it here once
// ─────────────────────────────────────────────────────────────────

import type { APIRoute } from 'astro';

export const GET: APIRoute = ({ site }) => {
  // site comes from astro.config.mjs → site: 'https://gk360.pk'
  const siteUrl = site ?? 'https://gk360.pk';

  const robotsTxt = `# robots.txt for ${siteUrl}
# Auto-generated by Astro on every build — do not edit manually

User-agent: *
Allow: /

# Block build artifacts and API routes
Disallow: /_astro/
Disallow: /api/

# Block any admin or private pages you add later
# Disallow: /admin/
# Disallow: /dashboard/

# AI training opt-out (optional but recommended)
User-agent: GPTBot
Disallow: /

User-agent: Google-Extended
Allow: /

# Sitemap — auto-generated by @astrojs/sitemap on every build
Sitemap: ${siteUrl}/sitemap-index.xml
`;

  return new Response(robotsTxt, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      // Cache for 24 hours — Cloudflare will serve from edge
      'Cache-Control': 'public, max-age=86400',
    },
  });
};
