// src/pages/robots.txt.ts
// Place this file at: src/pages/robots.txt.ts

import type { APIRoute } from 'astro';

export const GET: APIRoute = ({ site }) => {
  // FIX: strip trailing slash from site URL to prevent double-slash in sitemap URL
  // Astro returns 'https://gk360.pk/' — we need 'https://gk360.pk'
  const siteUrl = (site?.toString() ?? 'https://gk360.pk').replace(/\/$/, '');

  const robotsTxt = `# robots.txt for ${siteUrl}
# Auto-generated by Astro on every build — do NOT edit this file manually.
# To make changes, edit src/pages/robots.txt.ts in your project.

# ─────────────────────────────────────────────────────────────
# GENERAL CRAWLERS — Allow everything
# ─────────────────────────────────────────────────────────────
User-agent: *
Allow: /
Disallow: /_astro/
Disallow: /api/

# ─────────────────────────────────────────────────────────────
# GOOGLE — Full access including AI features
# ─────────────────────────────────────────────────────────────
User-agent: Googlebot
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: Googlebot-Mobile
Allow: /

# Google's AI crawler (Gemini, SGE) — ALLOW so we appear in AI answers
User-agent: Google-Extended
Allow: /

# ─────────────────────────────────────────────────────────────
# BING & MICROSOFT — Full access
# ─────────────────────────────────────────────────────────────
User-agent: Bingbot
Allow: /

User-agent: msnbot
Allow: /

User-agent: msnbot-media
Allow: /

# Microsoft Copilot crawler — ALLOW for AI visibility
User-agent: Bingbot
Allow: /

# ─────────────────────────────────────────────────────────────
# OTHER MAJOR SEARCH ENGINES
# ─────────────────────────────────────────────────────────────
User-agent: Slurp
Allow: /

User-agent: DuckDuckBot
Allow: /

User-agent: Baiduspider
Allow: /

User-agent: YandexBot
Allow: /

User-agent: Sogou
Allow: /

User-agent: Exabot
Allow: /

User-agent: facebot
Allow: /

User-agent: ia_archiver
Allow: /

# ─────────────────────────────────────────────────────────────
# AI CRAWLERS — Allow all so GK360 appears in AI answers
# This is critical for AEO (Answer Engine Optimization)
# These crawlers feed ChatGPT, Claude, Perplexity, Gemini etc.
# ─────────────────────────────────────────────────────────────

# OpenAI / ChatGPT — ALLOW so students find us via ChatGPT
User-agent: GPTBot
Allow: /

# OpenAI SearchGPT
User-agent: OAI-SearchBot
Allow: /

# Anthropic / Claude
User-agent: anthropic-ai
Allow: /

User-agent: Claude-Web
Allow: /

# Perplexity AI
User-agent: PerplexityBot
Allow: /

# Meta AI (Llama, MetaAI)
User-agent: meta-externalagent
Allow: /

User-agent: FacebookBot
Allow: /

# Apple Applebot (Siri, Apple Intelligence)
User-agent: Applebot
Allow: /

User-agent: Applebot-Extended
Allow: /

# Common Crawl (used by many AI training datasets)
User-agent: CCBot
Allow: /

# Amazon Alexa
User-agent: ia_archiver
Allow: /

# Cohere AI
User-agent: cohere-ai
Allow: /

# You.com
User-agent: YouBot
Allow: /

# Brave Search
User-agent: Brave
Allow: /

# ─────────────────────────────────────────────────────────────
# BAD BOTS — Block scrapers and spam crawlers
# ─────────────────────────────────────────────────────────────
User-agent: AhrefsBot
Disallow: /

User-agent: SemrushBot
Disallow: /

User-agent: DotBot
Disallow: /

User-agent: MJ12bot
Disallow: /

User-agent: DataForSeoBot
Disallow: /

User-agent: BLEXBot
Disallow: /

User-agent: PetalBot
Disallow: /

# ─────────────────────────────────────────────────────────────
# SITEMAP — Auto-generated by @astrojs/sitemap on every build
# ─────────────────────────────────────────────────────────────
Sitemap: ${siteUrl}/sitemap-index.xml
`;

  return new Response(robotsTxt, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=86400',
    },
  });
};
